name: THEJB.AI
author: JB
description: "AI 논문 리뷰와 구현"

url: https://thejb.ai
img_baseurl: "https://img.thejb.ai"

link_icons:
  -
    icon: github-icon
    url: https://github.com/the-jb
  - 
    icon: blog-icon
    url: https://blog.thejb.ai
  -
    icon: scholar-icon
    url: https://scholar.google.com/citations?user=SQYbgngAAAAJ


permalink: /:title/

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: ''
    # line_numbers: true
    default_lang: python
    guess_lang: true

remote_theme: "the-jb/pages-theme"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

sass:
  style: :compressed

gems:

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME
