name: THEJB
author: JB

url: https://thejb.ai
img_baseurl: "https://img.thejb.ai"

link_icons:
  -
    icon: /github.svg
    url: https://github.com/the-jb
  -
    icon: /scholar.svg
    url: https://scholar.google.com/citations?user=SQYbgngAAAAJ

remote_theme: "the-jb/pages-theme"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

sass:
  style: :compressed

gems:

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME
